# Generated by Django 4.0.4 on 2022-05-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steamapp',
            fields=[
                ('appid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('developer', models.TextField(blank=True, max_length=255, null=True)),
                ('platforms', models.TextField(blank=True, max_length=255, null=True)),
                ('categories', models.TextField(blank=True, max_length=1000, null=True)),
                ('genres', models.TextField(blank=True, max_length=255, null=True)),
                ('achievements', models.IntegerField(blank=True, null=True)),
                ('positive_ratings', models.IntegerField(blank=True, null=True)),
                ('negative_ratings', models.IntegerField(blank=True, null=True)),
                ('average_playtime', models.FloatField(blank=True, null=True)),
                ('median_playtime', models.FloatField(blank=True, null=True)),
                ('owners', models.TextField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('header_image', models.TextField(blank=True, max_length=255, null=True)),
                ('background', models.TextField(blank=True, max_length=255, null=True)),
                ('detailed_description', models.TextField(blank=True, max_length=100000, null=True)),
                ('about_the_game', models.TextField(blank=True, max_length=100000, null=True)),
            ],
            options={
                'db_table': 'steam',
                'managed': False,
            },
        ),
    ]
