# Generated by Django 4.0.4 on 2022-05-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stima', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='steamapp',
            table='steamapp',
        ),
    ]
