# Generated by Django 4.0.4 on 2022-05-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stima', '0002_alter_steamapp_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='steamapp',
            table='steam',
        ),
    ]
