# Generated by Django 4.0.4 on 2022-05-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stima', '0003_alter_steamapp_table'),
    ]

    operations = [
        UnaccentExtension()
    ]
